# Don't know how Minecraft's §<color code> formatting works? Check out: https://www.digminecraft.com/lists/color_list_pc.php
[system]
version = "Version: %s"
githubBase = "GitHub: %s"
githubView = "View on GitHub"
modrinthBase = "Modrinth: %s"
modrinthView = "View on Modrinth"
curseforgeBase = "CurseForge: %s"
curseforgeView = "View on CurseForge"
reloadStart = "Reloading language file..."
reloadFinish = "Language file reloaded"
configChange = "Config file modified, reloading..."
languageChange = "Language file modified, reloading..."

[error]
# A message sent when the sender player does not exist (only happens when a command block runs the command)
senderNotExist = "Player does not exist"
# A message sent when the target player does not exist
receiverNotExist = "Target player does not exist"
# The message for when a player attempts to use /tpa or /tpahere on themselves
selfCommand = "You cannot use this command on yourself"
# The message displayed to the other player when the TPA request is from another dimension
crossDim = "Cannot teleport across dimensions: %s ↔ %s"
# The message displayed when the player accepting or sending a TPA request is too far away
tooFar = "Too far away (max %s blocks, currently %s blocks)"
# The message displayed when the player accepting or sending a TPA request is too close
tooClose = "Too close (min %s blocks, currently %s blocks)"

[error.request]
# A message sent when your teleport request could not be found
notfoundAll = "No teleport request found"
# A message sent when your teleport request for someone could not be found
notfoundTarget = "No teleport request to %s found"
# A message sent when a player tries to send a teleport request to a player who has blocked them
blockedSender = "You have been blocked by %s"
# A message sent when a player tries to send a teleport request to a player they have blocked
blockedReceiver = "You have blocked %s"
# A message sent when a player who has blocked all requests tries to send a teleport request
toggledSender = "You have TPA requests disabled. Use /tptoggle to re-enable."
# A message sent when a player tries to send a teleport request to a player who has blocked all teleport requests
toggledReceiver = "%s has TPA requests disabled"
# A message sent when a teleport request already exists
requestExist = "A teleport request to %s already exists"

[windup]
# A message sent when a command is waiting to be executed
remain = "Executing command, please wait %s second(s)"
# A message sent when waiting for the command to be executed, moved out of limit
outDistance = "Moved too far while executing /%s, cancelled"

[teleport]
# A message sent when player is waiting to be teleported
remain = "Teleporting, please wait %s second(s)"
# A message sent when waiting for being teleported, moved out of limit
outDistance = "Moved too far during teleport"

[cooldown]
# A message sent while the command is on cooldown
underCooldown = "/%s on cooldown, retry in %ss"

[toggle]
# A message sent when player enables toggle
on = "Auto-block all TPA requests"
# A message sent when player disables toggle
off = "Allow all TPA requests"

[block]
# A message sent when player successfully blocks someone
success = "Blocked all TPA requests from %s"
# A message sent when player fails to block someone
failure = "Failed to block TPA requests from %s"
# A message sent to someone who has been blocked
blockedPlayer = "You have been blacklisted by %s"

[unblock]
# A message sent when player successfully unblocks someone
success = "Unblocked all TPA requests from %s"
# A message sent when player fails to unblock someone
failure = "Failed to unblock TPA requests from %s"
# A message sent to someone who has been unblocked
unblockedPlayer = "You have been removed from %s's blacklist"

[back]
# A message sent when cannot find player's last death position
deathNotFound = "No last death location found"
# A message sent when player is being teleported
teleporting = "Teleporting to last death location..."
# A message sent when player has been teleported
teleported = "Teleported to last death location"

[tpa]
# A message sent to sender
requestSender = "Sent teleport request to %s"
# A message sent to receiver
requestReceiver = "%s wants to teleport to you!"
# A message sent to sender when request times out
timeoutSender = "Teleport request to %s timed out"
# A message sent to receiver when request times out
timeoutReceiver = "Teleport request from %s timed out"
# A message sent to sender when preparing for teleport
acceptSender = "Teleport request to %s accepted, preparing teleport..."
# A message sent to receiver when accepting request
acceptReceiver = "Accepted teleport request from %s"
# A message sent to sender when request is cancelled
cancelSender = "Teleport request to %s cancelled"
# A message sent to receiver when request is cancelled
cancelReceiver = "Teleport request from %s has been cancelled"
# A message sent to sender when request is refused
refuseSender = "%s refused your teleport request"
# A message sent to receiver when refusing request
refuseReceiver = "Refused teleport request from %s"

[tpaHere]
# A message sent to sender
requestSender = "Sent teleport request to %s"
# A message sent to receiver
requestReceiver = "%s wants you to teleport to them!"
# A message sent to sender when request times out
timeoutSender = "Teleport request to %s timed out"
# A message sent to receiver when request times out
timeoutReceiver = "Teleport request from %s timed out"
# A message sent to sender when preparing for teleport
acceptSender = "%s accepted the teleport request, preparing to teleport to you"
# A message sent to receiver when accepting request
acceptReceiver = "Accepted teleport request to %s, preparing teleport..."
# A message sent to sender when request is cancelled
cancelSender = "Teleport request to %s cancelled"
# A message sent to receiver when request is cancelled
cancelReceiver = "Teleport request from %s has been cancelled"
# A message sent to sender when request is refused
refuseSender = "%s refused your teleport request"
# A message sent to receiver when refusing request
refuseReceiver = "Refused teleport request from %s"
