name: Release

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'liberica'
                  cache: 'gradle'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Run Detekt
              run: ./gradlew detekt

            - name: Build
              run: ./gradlew build

            - name: Publish to GitHub, Modrinth & CurseForge
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: QuPbmyCQ
                  modrinth-featured: false
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

                  curseforge-id: 945501
                  curseforge-token: ${{ secrets.CF_API_TOKEN }}

                  github-token: ${{ secrets.GITHUB_TOKEN }}

                  loaders: |
                      fabric

                  files: |
                      build/libs/!(*-@(dev-all|sources)).jar
                      build/libs/*-@(dev-all|sources).jar
